### PR TITLE
feat: output can be stdout so you can pipe it to other commands

### PR DESCRIPTION
**Pull request by imreACTmd**
output now accepts '-' and sends the output to stdout so you can pipe it to other commands.

### CODE REVIEW

**Comment by imreACTmd** [comment]
@rap2hpoutre what do you think of this PR?

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! 

Why did you change all `console.log` to `console.error`? It could seem weird to `console.error` a "process started" info.

**Comment by imreACTmd** [comment]
I had to switch the logging statements to STDERR because the new feature is output to STDOUT, and otherwise the log statements would end up in STDOUT and potentially mess up the resulting pg_dump output.

**Comment by imreACTmd** [comment]
@rap2hpoutre If you prefer me to do it differently, let me know! It's easy enough to change.

**Comment by imreACTmd** [comment]
@rap2hpoutre does it look good to you?

**Comment by rap2hpoutre** [comment]
> I had to switch the logging statements to STDERR because the new feature is output to STDOUT, and otherwise the log statements would end up in STDOUT and potentially mess up the resulting pg_dump output.

That's OK then!

> @rap2hpoutre does it look good to you?

Sorry for late answer! Yes we can merge it.

Thank you for your work!!!

**Review by rap2hpoutre — APPROVED** [review]
You can click on squash+merge!

**Pull request merged**
